[package]
name = "ypdf-desktop"
description = "yPDF desktop application."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ypdf"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
directories = "6.0.0"
eframe = "0.35.0"
egui = "0.35.0"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tracing = "0.1.44"
ypdf-core = { path = "../../crates/ypdf-core" }
ypdf-doc = { version = "0.1.0", path = "../../crates/ypdf-doc" }
ypdf-optimize = { version = "0.1.0", path = "../../crates/ypdf-optimize" }
ypdf-render = { version = "0.1.0", path = "../../crates/ypdf-render" }
ypdf-security = { version = "0.1.0", path = "../../crates/ypdf-security" }
ypdf-crypt = { version = "0.1.0", path = "../../crates/ypdf-crypt" }
ypdf-ocr = { version = "0.1.0", path = "../../crates/ypdf-ocr" }
ypdf-watermark = { version = "0.1.0", path = "../../crates/ypdf-watermark" }
ypdf-redact = { version = "0.1.0", path = "../../crates/ypdf-redact" }
ypdf-outline = { version = "0.1.0", path = "../../crates/ypdf-outline" }
ypdf-forms = { version = "0.1.0", path = "../../crates/ypdf-forms" }
ypdf-annot = { version = "0.1.0", path = "../../crates/ypdf-annot" }
crossbeam-channel = "0.5.16"
